# ref https://bbgithub.dev.bloomberg.com/bbgo/gobas/blob/main/.drone.yml
clone:
  git:
    image: plugins/git
    depth: 10
pipeline:
  build:
    image: artprod.dev.bloomberg.com/bbgo/golang:1.18
    commands:
      - go build -mod=readonly
  test:
    image: artprod.dev.bloomberg.com/bbgo/golang:1.18
    commands:
      - go test -mod=readonly -coverprofile="coverage.out" ./...
  lint:
    image: artprod.dev.bloomberg.com/bb-rapidci/drone/plugins/bb/golangci-lint:1.46.2
    environment:
      - GOPROXY=https://goproxy.dev.bloomberg.com,direct
      - GOPRIVATE=bbgithub.dev.bloomberg.com
    commands:
      - go get ./...
      - golangci-lint run
  code-analysis:
    image: artprod.dev.bloomberg.com/bb-rapidci/drone/plugins/sonarqube
    pull: true
